// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Blogs            string
	Comments         string
	SchemaMigrations string
	Users            string
}{
	Blogs:            "blogs",
	Comments:         "comments",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
